#ifndef DECOMPRESS_H
#define DECOMPRESS_H

#define DECOMPRESS_ENTRY_OFFSET 1
#define DECOMPRESS_DELTA_SIZE_OFFSET 19
#define DECOMPRESS_DELTA_START_OFFSET 33
#define DECOMPRESS_PRGM_SIZE_OFFSET 41
#define DECOMPRESS_COMPRESSED_COPY_OFFSET 61
#define DECOMPRESS_COMPRESSED_END_OFFSET 49
#define DECOMPRESS_UNCOMPRESSED_END_OFFSET 53
#define DECOMPRESS_COMPRESSED_START_OFFSET 65
#define DECOMPRESS_UNCOMPRESSED_SIZE_OFFSET 70
#define DECOMPRESS_RESIZE_OFFSET 80
#define DECOMPRESS_RESIZE_SIZE_OFFSET 76

extern unsigned char decompress[];
extern unsigned int decompress_len;

#endif
